# Generated by Django 5.0.3 on 2024-10-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='number_of_srudents',
            new_name='number_of_students',
        ),
    ]
