# Generated by Django 5.0.3 on 2024-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_number_of_srudents_teacher_number_of_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=30),
        ),
    ]
